### ISSUE TITLE
Launchpad NFTs

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/mxc-marketplace#10]
![Image](https://github.com/MXCzkEVM/mxc-marketplace/assets/49724027/50d4dd88-61a8-46c8-929e-5a71141b18f2)

![Image](https://github.com/MXCzkEVM/mxc-marketplace/assets/49724027/d2d87b0c-54f8-43da-9f9f-45eab4de6d30)

**Comment by hairyf** [comment]
@SanghamitraBhowmick1993 deployed geneva

**Comment by SanghamitraBhowmick1993** [comment]
Questions:

1. How did you create/add the BlueberryRing category within the Launchpad?
2. I tried 'mint launchpad' and after approvals, I was able to see an item entry. After that, the flow was the same as for NFTs (list in marketplace, etc.). Is this the expected flow?

**Comment by SanghamitraBhowmick1993** [comment]
Users will not be able to create a launchpad but they can mint one. Once they mint, after approvals, they will see an item entry. After that, the flow is the same as for NFTs (list in the marketplace, etc.). and the flow in this sequence is working as expected.

I tried listing this for sale and it works
https://geneva-nft.moonchain.com/collection/0x30FA89a04325627BCb696A54dabAc0b82602A179/2



![Image](https://github.com/MXCzkEVM/mxc-marketplace/assets/93600163/ecc06400-08a7-407b-b238-90137d846690)
