### ISSUE TITLE
Sorting of hexagons on NFT dApp

### ISSUE THREAD

**Issue by SanghamitraBhowmick1993** [MXCzkEVM/mxc-marketplace#4]
<img width="648" alt="image" src="https://github.com/MXCzkEVM/mxc-marketplace/assets/93600163/6940583b-dd49-4f0e-9621-ae3b54d98ff4">
<img width="676" alt="image" src="https://github.com/MXCzkEVM/mxc-marketplace/assets/93600163/6b1fabc2-60f8-4b01-9455-5fe49f833b7c">

**Comment by SanghamitraBhowmick1993** [comment]
blocked due to bug https://github.com/orgs/MXCzkEVM/projects/3/views/1?pane=issue&itemId=59804341

**Comment by hairyf** [comment]
#6 fixed, you can continue testing @SanghamitraBhowmick1993

**Comment by SanghamitraBhowmick1993** [comment]
Attempted testing with two different listings. However, when attempting to mint hexagon for the second time, the transaction takes an unusually long time to complete and remains in pending status.

https://geneva-explorer.moonchain.com/tx/0x5cf2850463e15829c1b872b7de21b95270733c68907c3670d131f1cc54410e55 


![Image](https://github.com/MXCzkEVM/mxc-marketplace/assets/93600163/ea6d4f32-18ff-4557-ad1b-ffb971f536a2)

also blocked due to https://github.com/orgs/MXCzkEVM/projects/3/views/1?pane=issue&itemId=60011786

**Comment by hairyf** [comment]
> Attempted testing with two different listings. However, when attempting to mint hexagon for the second time, the transaction takes an unusually long time to complete and remains in pending status.

It should be caused by gas fee fluctuations, and the transaction has been completed.

**Comment by SanghamitraBhowmick1993** [comment]
Sorting hexagons isn't functioning properly, and when I list one for sale at 100, it doesn't appear on the homepage; it still shows as "Not listed."

Issue replication available here - https://github.com/MXCzkEVM/mxc-marketplace/assets/93600163/08fdc9ef-9c3d-42fe-8fbb-d20ec797365e

**Comment by hairyf** [comment]
trying it out

**Comment by SanghamitraBhowmick1993** [comment]
Working as expected


![Image](https://github.com/MXCzkEVM/mxc-marketplace/assets/93600163/34d4cb98-f71e-41d9-b20f-6975cab6a911)
