### ISSUE TITLE
Unable to see minted hexagons in NFT dapp - Geneva

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/mxc-marketplace#5]
Below screenshot is the minted hexagon visible in mapper
![Image](https://github.com/MXCzkEVM/mxc-marketplace/assets/93600163/cb43379b-6d9a-4546-9536-da9578a32984)

Below screenshot is when i navigate to NFT - Hexagon
![Image](https://github.com/MXCzkEVM/mxc-marketplace/assets/93600163/433da6a0-01b7-445d-984d-a4af8f3f3a1d)

**Comment by SanghamitraBhowmick1993** [comment]
blocked due to bug https://github.com/orgs/MXCzkEVM/projects/3/views/1?pane=issue&itemId=59804341

**Comment by SanghamitraBhowmick1993** [comment]
this is working


![Image](https://github.com/MXCzkEVM/mxc-marketplace/assets/93600163/b596f3fa-9903-407e-b5f5-19545a918349)
