### ISSUE TITLE
Hexagon Ownership Display Issue in MNS

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/mxc-marketplace#6]
I can see the minted hexagon in MNS, but the current owner field does not display my wallet address. Instead, it shows a constant value as '0x1964F08f56b79051fB3AE9a2C4d8D92A059b1237

![Image](https://github.com/MXCzkEVM/mxc-marketplace/assets/93600163/df0159ad-63e9-4c0d-9ccb-59958bc762e6)

**Comment by hairyf** [comment]
fixed

**Comment by SanghamitraBhowmick1993** [comment]
this is working


![Image](https://github.com/MXCzkEVM/mxc-marketplace/assets/93600163/477830c0-dfbf-43a2-9998-f33d283882c4)
