### ISSUE TITLE
Inconsistency in Hexagon Visibility on Moonchain NFT Profile

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/mxc-marketplace#7]
When attempting to mint two hexagons, both items are visible in the user's profile page (https://geneva-nft.moonchain.com/profile/0x0795D90c6d60F7c77041862E9aE5059B4d5e0d7A), but only one hexagon appears in the account's hexagons section (https://geneva-nft.moonchain.com/hexagons). This inconsistency suggests a discrepancy in the visibility or tracking of minted hexagons within the same account.

Screenshot 1:

![Image](https://github.com/MXCzkEVM/mxc-marketplace/assets/93600163/19e382e7-2905-4f5c-9035-b285930694f5)

Screenshot 2:

![Image](https://github.com/MXCzkEVM/mxc-marketplace/assets/93600163/19e732e8-a89d-4023-a12a-a1eb75abb61c)

**Comment by SanghamitraBhowmick1993** [comment]
this is on hold due to https://github.com/orgs/MXCzkEVM/projects/3/views/1?pane=issue&itemId=59181029

**Comment by SanghamitraBhowmick1993** [comment]
this is working
